### ISSUE TITLE
Usage Docs with caveman2

### ISSUE THREAD

**Issue by daninus14** [eudoxia0/clack-errors#14]
Hi, can you please add docs on how to use this with the standard project generated with caveman2?

**Comment by eudoxia0** [comment]
Unfortuntely I probably won't. I haven't used Common Lisp in depth in years, and I lost track of Clack development after the great Clack/lack shift, my other web framework hasn't built properly in years and this one probably doesn't either.

So you might want to fork this and update it, or do your own thing.
