### ISSUE TITLE
Does not build today - clack changes?

### ISSUE THREAD

**Issue by quicklisp** [eudoxia0/clack-errors#5]
I get this today:

    Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {100410F6C3}>: The name "CLACK.RESPONSE" does not designate any package.

More context is in this log: http://report.quicklisp.org/2015-04-28/failure-report/clack-errors.html#clack-errors

**Comment by eudoxia0** [comment]
Quite probably. I'll look into this now, at least now I have a reason to upgrade to Djula templates among other things.
