### ISSUE TITLE
The document should be updated

### ISSUE THREAD

**Issue by VitoVan** [eudoxia0/clack-errors#7]
This is the demo:
```Lisp
(defun start ()
  (setf *handler*
        (clack:clackup
         (funcall clack-errors:*clack-error-middleware*
                  *app*
                  :debug t)
         :port 8000)))

(defun stop ()
  (clack:stop *handler*))
```

And this is the doc:

```Lisp
(clack:clackup
  (builder
    (clack-errors:<clack-error-middleware>
      :debug (getf (envy:config :myapp) :debug))
    *app*))
```

This almost kill me.

**Comment by coseltech** [comment]
I'd just like a confirmation whether this package is supposed to work with Lucerne.

**Comment by VitoVan** [comment]
@coseltech Seems the author has been disappeared long long ago.

**Comment by eudoxia0** [comment]
Reports of my disappearance are greatly exaggerated.

@coseltech it's built into Lucerne already. The `start` function takes a `debug` keyword argument which enables it.
